### PR TITLE
Paragraph spans

### LINKED ISSUE #125: Nested lists show multiple bullets
screenshot_1478255998

A list within a list like 
```
<ul>
   <li>Item
   <ul>
      <li>Inner item</li>
   </ul>
   </li>
</ul>
```
should probably only show the innermost bullet (but still keep the indenting).

### LINKED ISSUE #126: Nested lists get removed
When going from visual mode to HTML, the inner nested lists get removed.

### Expected

```
<ul>
   <li>Item
   <ul>
      <li>Inner item</li>
   </ul>
   </li>
</ul>
```

### Observed

```
<ul>
   <li>Item</li>
</ul>Inner item
```

### Reproduced
1. Start with a nested list inside a list
2. Switch to visual mode
3. Switch back to HTML mode and notice the change

### PR DESCRIPTION
**Pull request by hypest**
### Fix #125, #126, #170, #188, #194, #247 (but with a new issue), #251, #264

🎉 

This PR introduces a different method of marking and handling block elements. Here's a list of the changes it introduces:
* Mark the whole content of a block with the span
* Set the block spans with the `SPAN_PARAGRAPH` flag and never change it. See the [Spanned.java source](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/text/Spanned.java#L72-L88) for details. Paragraph spans must start after a newline (or the start of buffer) and end right after a newline (or the end of the buffer). The auto-changing nature of the SPAN_PARAGRAPH span becomes tricky when text is replaced instead of just added/removed and a few classes are dedicated to handling that ([ParagraphBleedAdjuster](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/experiment/paragraph-spans/aztec/src/main/kotlin/org/wordpress/aztec/watchers/ParagraphBleedAdjuster.kt), [ParagraphCollapseAdjuster](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/experiment/paragraph-spans/aztec/src/main/kotlin/org/wordpress/aztec/watchers/ParagraphCollapseAdjuster.kt), [ParagraphCollapseRemover](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/experiment/paragraph-spans/aztec/src/main/kotlin/org/wordpress/aztec/watchers/ParagraphCollapseRemover.kt))
* Each block element/span has a `nestingLevel` field, corresponding to its nesting level in html
* Block spans are sorted by position and nesting and then exported recursively to html
* Code that performs each block element's behaviour (list, listitem, heading, quote) runs "in parallel" to the other block elements to enforce a separation of concerns between the various types of block elements. AztecText's text mutation (like deleting the double-newline to close a quote) happens only after all block handlers have finished their processing.
* Listitem behaviour handling is implemented in a separate handler than the List itself
* Double-enter at block's end closes only the inner block when nested. This allows editing in the outer block to continue.
* Complex conditionals are split into series of simpler conditionals that return early in order to make the algorithm more readable. [Example](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/experiment/paragraph-spans/aztec/src/main/kotlin/org/wordpress/aztec/AztecParser.kt#L172-L209).

Known issues:
* Text is now never empty (there's a ZWJ if buffer empty) so, hint text is never shown. We can prolly tackle that in a separate PR.
* Nested blockquotes inside lists don't show the bullet/number of the list item they're on

This is a fairly big and broad PR, sorry for that :(. The changes are too close to the core to keep it small though. I'm open to ideas on how to break it down to smaller PRs if needed :). Thanks!

### CODE REVIEW

**Comment by theck13** [comment]
Add https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/264 to the list of fixes.  Thanks, @hypest!

**Comment by hypest** [comment]
Added a couple of commits (76b356e, 1a438af) that fix an issue where closing a nested list didn't properly close the parent list item.

Also added a fix for #125 (Nested lists show multiple bullets) with commits f068746 and 8ec075c.

**Comment by hypest** [comment]
Fixed (with 6981223) a rather "invisible" regression that happened with 56f9427.

**Comment by 0nko** [comment]
Awesome work, @hypest! 
:shipit:

**Pull request merged**
