### PR TITLE
Replace unknown HTML with a drawable

### LINKED ISSUE #8: Make UnknownHtmlSpan visually interesting
It's just a white rectangle for now. We should display a placeholder drawable.

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #8

### CODE REVIEW

**Comment by theck13** [comment]
:shipit:

**Comment by theck13** [comment]
It looks like there is a merge conflict with https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/22.  After resolving the conflicts, the app crashes with this stack trace when trying to select the drawable.
```
07-22 15:12:13.942 7450-7450/org.wordpress.aztec E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.aztec, PID: 7450
    java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 82]
        at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
        at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
        at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4260)
        at android.widget.Editor$HandleView.updatePosition(Editor.java:3708)
        at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2507)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by 0nko** [comment]
I've merged `develop` with changes from #22 and it seems to be working fine on my phone. Can you confirm?

**Comment by theck13** [comment]
It works for me after `git pull`.

**Comment by theck13** [comment]
:shipit:

**Pull request merged**
