### PR TITLE
Issue/50 strikethrough support

### LINKED ISSUE #50: Add support for Strikethrough
Add Strikethrough button to toolbar and make sure it works nicely as standalone style or as mix with other styles.

### PR DESCRIPTION
**Pull request by khaykov**
This PR adds Strikethrough style support, toolbar button and tests.

This PR also combines the logic for inline styles, as they use common `CharacterStyle` span. This allows us to easily plug-and-use any other inline styles (like underline).

Fixes #50

### CODE REVIEW

**Comment by 0nko** [comment]
When I select the last word _Hidden_ in the demo and click on the strikethrough button I get this exception:

```
java.lang.IndexOutOfBoundsException: setSpan (75 ... -1) has end before start
    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1083)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
    at org.wordpress.aztec.AztecText.joinStyleSpans(AztecText.kt:207)
    at org.wordpress.aztec.AztecText.applyInlineStyle(AztecText.kt:338)
    at org.wordpress.aztec.AztecText.strikethrough(AztecText.kt:171)
    at org.wordpress.aztec.AztecText.toggleFormatting(AztecText.kt:845)
    at org.wordpress.aztec.toolbar.AztecToolbar.onToolbarAction(AztecToolbar.kt:114)
    at org.wordpress.aztec.toolbar.AztecToolbar.access$onToolbarAction(AztecToolbar.kt:15)
    at org.wordpress.aztec.toolbar.AztecToolbar$initView$1.onClick(AztecToolbar.kt:51)
    at android.view.View.performClick(View.java:5198)
    at android.widget.CompoundButton.performClick(CompoundButton.java:122)
    at android.view.View$PerformClick.run(View.java:21147)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by khaykov** [comment]
I missed the fact that HiddenHtmlSpan is also a CharacterSpan, and tried to do stuff with it. Added a check for it (and test), so this crash should be fixed :)

Also, while fixing this issue found interesting behaviour of HiddenHtmlSpan -> #54

**Comment by 0nko** [comment]
Nice. I'll take a look what's going on..

**Comment by 0nko** [comment]
Looks good. :shipit:

**Pull request merged**
