### PR TITLE
Issue/167 block editing

### PR DESCRIPTION
**Pull request by 0nko**
Adresses #167.

When you click on an unknown HTML question mark picture a dialog will pop up and you can edit the unknown HTML and save it.

I haven't made the unknown HTML a block span because that would create problems if it was embedded inside another block element and I don't see any issues as it is right now.

### CODE REVIEW

**Comment by khaykov** [comment]
I noticed a bit weird behavior:
Open hidden dialog with hidden html in demo app.
Add `<b>` tags around "Menu", so the html will look like this:
`<iframe class="classic"><b>Menu</b></iframe>`
Press save, and open hidden tag again.
`<b>` get's escaped, and html looks like this:
`<iframe class="classic">&lt;b&gt;Menu&lt;/b&gt;</iframe>`

Another minor issue is that the long code get's clipped at the bottom of the dialog:
screenshot-2017-02-10_15 41 41 543

**Comment by khaykov** [comment]
Cursor related issue:

Open demo app.
Go to source code, copy everything.
Return to visual mode.
Open Hidden html tag and replace "Menu" with copied code.
Click save.
Notice "aztec_cursor" appearing at the end of the editor.

**Comment by 0nko** [comment]
At last, all of the issues should be fixed. Ready for another pass.

**Comment by 0nko** [comment]
OK, now :P.

**Comment by khaykov** [comment]
Thanks for the changes, everything works nicely now!
I noticed only one minor thing - when there is a lot of content in dialog, the keyboard overlaps it, and bottom of dialog becomes hidden. It's especially noticeable in landscape mode.

Maybe setting soft input mode of dialog window to something like `SOFT_INPUT_ADJUST_RESIZE` will help?

**Comment by 0nko** [comment]
Thanks for the tip!

**Comment by khaykov** [comment]
:shipit: 🎉

**Pull request merged**
