### PR TITLE
Issue/source dialog style

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Use app styling for source view dialogs (e.g. unknown tag editing).

### Test
1. Launch demonstration app.
2. Tap unknown tag (i.e. ***?*** icon).
3. Notice dialog style.

### CODE REVIEW

**Comment by 0nko** [comment]
It works well in a dialog and in the demo app, but when I tried to use the branch in WordPress, the source text is invisible:

image

**Comment by theck13** [comment]
That screenshot looks like the HTML view rather than a dialog.  Can you share the branch you were testing?

**Comment by 0nko** [comment]
Yes, it's the HTML view. It looks fine in the dialog. I was testing it on `develop`.

**Comment by 0nko** [comment]
Perfect, that fixed it! :shipit:

**Pull request merged**
