### PR TITLE
Issue/1 add unit tests

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add unit test utility class and basic unit tests for parsing HTML as described in https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/1.

### Test
<ol><b>Run All Tests</b>
<li> Open <tt>AztecParserTest.kt</tt> file.</li>
<li> Click Run icon next to <tt>AztecParserTest</tt> shown below.</li>
<li> Choose run option.</li>
</ol>

test_all

<ol><b>Run One Test</b>
<li> Open <tt>AztecParserTest.kt</tt> file.</li>
<li> Click Run icon next to test in question like <tt>parseFromAndToHtmlBold_isEqual</tt> shown below.</li>
<li> Choose run option.</li>
</ol>

test_one

The following tests are failing.  We should check `AztecParser` for correctness.
- `parseFromAndToHtmlAll_isEqual`
- `parseFromAndToHtmlBullet_isEqual`
- `parseFromAndToHtmlQuote_isEqual`
- `parseFromAndToHtmlStrikethrough_isEqual`
- `parseFromAndToHtmlUnknown_isEqual`

### CODE REVIEW

**Comment by 0nko** [comment]
Looks good. I'd say we merge it and resolve the failing tests in separate issues. This way we can add more unit tests for new tags and spans while other tests are being fixed.

**Comment by theck13** [comment]
That means all future merges will fail until we fix the tests.  If that's okay, go ahead and merge, but we should prioritize those test fixes.

**Comment by 0nko** [comment]
As @maxme suggested, we could comment out the 5 failing tests and uncomment them later when they get fixed.

**Comment by theck13** [comment]
The following tests were commented out.
- `parseHtmlToSpanToHtmlAll_isEqual`
- `parseHtmlToSpanToHtmlBullet_isEqual`
- `parseHtmlToSpanToHtmlQuote_isEqual`
- `parseHtmlToSpanToHtmlStrikethrough_isEqual`
- `parseHtmlToSpanToHtmlUnknown_isEqual`

**Pull request merged**
