### PR TITLE
Updating gradle to 2.2.0

### PR DESCRIPTION
**Pull request by khaykov**
Bumping gradle version to 2.2.0

### CODE REVIEW

**Comment by khaykov** [comment]
Look like the the Robolectric doesn't [work well](https://github.com/robolectric/robolectric/issues/2647#issuecomment-248831873) with gradle 2.2.0 yet.

**Comment by 0nko** [comment]
@khaykov, @theck13: Can you try it out? Seems to work for me.

**Comment by theck13** [comment]
Travis still fails for me.  It looks like a [fix](https://github.com/robolectric/robolectric/pull/2673) was [released](https://github.com/robolectric/robolectric/releases/tag/robolectric-3.1.4).  Are you still running `org.robolectric:robolectric:3.1` without issue?

**Comment by 0nko** [comment]
I updated Robolectric to version 3.1.4 and it works on my machine. I just wanted to know if you can run tests locally. Travis fails because of this:
```
You have not accepted the license agreements of the following SDK components:
[Android SDK Platform 25, Android SDK Build-Tools 24.0.3].
```

**Comment by theck13** [comment]
I can run tests locally.

Gradle is up to `2.2.3` now and it looks like it will be `2.3.0` soon according to [Bintray](https://bintray.com/android/android-tools/com.android.tools.build.gradle).

**Comment by 0nko** [comment]
Yup, I updated gradle, too.

**Comment by 0nko** [comment]
So it seems the problem was that the compile SDK version was 25 but build tools version was 24. This is now fixed and ready to be merged.

**Comment by theck13** [comment]
:shipit:

**Pull request merged**
