### PR TITLE
Issue/fix cursor inside unknown html

### PR DESCRIPTION
**Pull request by khaykov**
This PR fixes issue with cursor not working correctly inside uknown html tag.

### CODE REVIEW

**Comment by 0nko** [comment]
It's not a big deal, but if switch to HTML and leave the cursor inside the `<iframe>` tag, switch to visual and then back to HTML , you'll notice an extra newline is inserted.

**Comment by khaykov** [comment]
I think you are talking about the case when some text is on same line as unknown html span. This is actually the original behavior of the parser, and not related to cursor. When you switch from source to visual editor, the "html" that is passed to it, is actually mix of html and EditText markup - so the text with unknown html span on same line will look like this -> `text\n<iframe class="classic">Menu</iframe>`. Space is being added [here](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/java/org/wordpress/aztec/Html.java#L938) to replace a newline symbol. I'm still not sure why it's like this, but will take a look.

**Comment by khaykov** [comment]
@0nko Ready for another pass :)

**Comment by 0nko** [comment]
Cool! :shipit:

**Pull request merged**
